# Generated by Django 5.2.12 on 2026-04-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='type',
        ),
    ]
