# Generated by Django 5.2.12 on 2026-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_books_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('ilmiy', 'Ilmiy'), ('badiiy', 'Badiiy')], default='standard', max_length=255),
        ),
    ]
